### ISSUE TITLE
after_get_object returning an object

### ISSUE THREAD

**Issue by etiennecaldo** [miLibris/flask-rest-jsonapi#107]
Hi,
Would you accept a PR allowing after_get_object (and perhaps all after_*_object) to return an object. Indeed, I want to be able to filter objects depending on if the user has right to see it or not.

This would give this code:
```
obj = self.retrieve_object(view_kwargs)
obj = self.after_get_object(obj, view_kwargs)
```
instead of 
```
obj = self.retrieve_object(view_kwargs)
self.after_get_object(obj, view_kwargs)
```

This is already working today like this for collections:

```
collection = query.all()
collection = self.after_get_collection(collection, qs, view_kwargs)
```

Why not use same logic for single object?
I may submit something, let me know if you are OK and if you want me to do it for all after_*_object methods.
Thanks a lot for your answer.

**Comment by akira-dev** [comment]
Yes it is a good idea make PR please.
Thanks
