### ISSUE TITLE
MongoDataLayer

### ISSUE THREAD

**Issue by Esteban-De-la-Sexface** [miLibris/flask-rest-jsonapi#11]
When instantiating a MongoDataLayer connection the following call in resource.py
object_count, objects = self.data_layer.get_collection(qs, **kwargs)

passes a querystring

this method has no params in mongo.py

{
  "errors": [
    {
      "status": 500,
      "source": "",
      "detail": "get_collection() takes exactly 1 argument (2 given)",
      "title": "Unknow error"
    }
  ]
}

**Comment by akira-dev** [comment]
Test with the data layer i have sent to you
