### ISSUE TITLE
Swagger Documentation?

### ISSUE THREAD

**Issue by CaptObvious** [miLibris/flask-rest-jsonapi#12]
Are there any plans to implement Swagger integration so we can easily generate API documentation?

**Comment by ytjohn** [comment]
We've been using flask-restful and [flask-resful-swagger](https://github.com/rantav/flask-restful-swagger). It only implements swagger 1.2, but they are working on adding 2.0.  We also implement jsonapi (manually, I guess you'd say). So something that could automate building jsonapi rest interfaces and provide a swagger document reference would be a nice product for us.

**Comment by akira-dev** [comment]
No because Swagger documentation is based on api description made with swagger specification (OpenApi) that is not compatible with JSONAPI 1.0 specification. Swagger documentation tool is part of the Swagger software suite and I don't want to get closer to this environement.

**Comment by akouminov** [comment]
checkout this package https://apispec.readthedocs.io/en/latest/using_plugins.html
