### ISSUE TITLE
how do you override Content-Type / Accept headers?

### ISSUE THREAD

**Issue by tuxpowered** [miLibris/flask-rest-jsonapi#13]
I am trying to write an API receiver, where I can not control the other end. The other end _only_ allows headers 'Accept: application/json' and 'Content-Type: application/json'

What is the fastest way to accept and return application/json in the headers?

**Comment by nuthingman** [comment]
I'm having the same problem. I think this is where the checking is done https://github.com/miLibris/flask-rest-jsonapi/blob/master/flask_rest_jsonapi/decorators.py

Not sure how to proceed from here.

**Comment by tuxpowered** [comment]
it also appears hardcoded here: https://github.com/miLibris/flask-rest-jsonapi/blob/master/flask_rest_jsonapi/resource.py

**Comment by akira-dev** [comment]
The content-type and accept headers are related to the jsonapi 1.0 specification so i have not planned to make it configurable but you can try to override it via decorators
