### ISSUE TITLE
Authentification & limitation of operation

### ISSUE THREAD

**Issue by schuon** [miLibris/flask-rest-jsonapi#15]
Hi,
thanks for building this module. Have you considered how user authentification and limits to operation (e.g. only allow Read) could be handled? Something like the decorators from Flask-Security would be neat!
Cheers,
Sebastian

**Comment by akira-dev** [comment]
Yes in my own api project I have something like that :

```python
from flask_rest_jsonapi import ResourceList
from my_project.models import Item
from my_project.extensions import oauth2, sql_db
from my_project.permission.decorators import has_permission
from my_project.schemas.item import ItemSchema


class ItemList(ResourceList):
    schema = ItemSchema
    data_layer = {'session': sql_db.session,
                  'model': Item}
    get_decorators = [has_permission('item', 'list_items'), oauth2.require_oauth('item_list')]
    post_decorators = [has_permission('item', 'create_item'), oauth2.require_oauth('item_create')]
```

**Comment by schuon** [comment]
Stupid me, I found it now also in the docs (for future readers, it's here http://flask-rest-jsonapi.readthedocs.io/en/latest/resource_manager.html). 

Thanks!
