### ISSUE TITLE
pagination.py - 'data' is a list but accessed as a dict?

### ISSUE THREAD

**Issue by nemmons** [miLibris/flask-rest-jsonapi#25]
When i make an API call to my flask app running this library, i get the following error:

> File "/home/nate/.virtualenvs/flask-insure/lib/python3.5/site-packages/flask_rest_jsonapi/pagination.py", line 53, in add_pagination_links
>     data['links'] = links
> **TypeError: list indices must be integers or slices, not str**

When i debug my app, I see that data (passed from [ResourceView.get()](https://github.com/miLibris/flask-rest-jsonapi/blob/master/flask_rest_jsonapi/resource.py#L117))is a list of objects, but then [the line in question](https://github.com/miLibris/flask-rest-jsonapi/blob/master/flask_rest_jsonapi/pagination.py#L53) is accessing the list as if it were a dictionary. I followed the documentation as closely as possible and my setup so far is extremely bare-bones (see [here](https://pastebin.com/iuDWKr9g)). Can you see any issues in my setup, and if not can you think of any other reason this is happening?

Thanks for any help you can provide, and thanks for creating such a cool library with such thorough and detailed documentation!

**Comment by karec** [comment]
Simple question here : did you use raw marshmallow `Schema` or marshmallow-jsonapi `Schema` (https://github.com/marshmallow-code/marshmallow-jsonapi) ? 

flask-rest-jsonapi has been built to use marshmallow-jsonapi `Schema` class, which overload classic marshmallow `Schema` to return a compliant JSONAPI 1.0 json response even with `many=True` instead of a simple list

**Comment by nemmons** [comment]
I'm using the marshamallow-jsonapi schema (`from marshmallow_jsonapi.flask import Schema`)

**Comment by nemmons** [comment]
Ah, i figured it out, mostly. There was an error processing one of my fields, so Schema.dump() didn't invoke the POST_DUMP processor. Schema.dump() returns a tuple of the errors and the data, but [resource.py](https://github.com/miLibris/flask-rest-jsonapi/blob/master/flask_rest_jsonapi/resource.py#L117) doesn't currently handle and report errors. I might get ambitious and submit a pull request to handle errors here, or at least attempt it. Thanks for the help @karec, you definitely pointed me in the right direction!

**Comment by BANOnotIT** [comment]
#85
