### ISSUE TITLE
Decorator wrapping when creating new Resource class

### ISSUE THREAD

**Issue by kypsibir** [miLibris/flask-rest-jsonapi#27]
Every time new Resource class instantiates, methods (get, post, patch, put) are wrapped with check_headers decorator. Wrapping occures on class level. For example, after creating ten Resource classes, there are ten same decorators wrapping get method.
https://github.com/miLibris/flask-rest-jsonapi/blob/master/flask_rest_jsonapi/resource.py#L39
Since Flask [creates new instance](https://github.com/pallets/flask/blob/master/flask/views.py#L83) of View class (which is inherited by Resource) with every incoming request, in the end there are lots of same decorators wrapping (get, post, patch, put) methods. That causes RecursionError at some point.

**Comment by philof** [comment]
Each request adds more function calls until Python fails with a RecursionError

```
--------------------------------------------------------------------------------
127.0.0.1 - - [08/Apr/2017 15:46:50] "GET /persons HTTP/1.1" 200 -
--------------------------------------------------------------------------------
PATH: '/persons'
         4843 function calls (4766 primitive calls) in 0.013 seconds

--------------------------------------------------------------------------------
127.0.0.1 - - [08/Apr/2017 15:46:55] "GET /persons HTTP/1.1" 200 -
--------------------------------------------------------------------------------
PATH: '/persons'
         4896 function calls (4818 primitive calls) in 0.017 seconds

--------------------------------------------------------------------------------
127.0.0.1 - - [08/Apr/2017 15:46:56] "GET /persons HTTP/1.1" 200 -
--------------------------------------------------------------------------------
PATH: '/persons'
         4951 function calls (4872 primitive calls) in 0.026 seconds

```
Final call
```		 
--------------------------------------------------------------------------------
127.0.0.1 - - [08/Apr/2017 15:48:37] "GET /persons HTTP/1.1" 200 -
--------------------------------------------------------------------------------
PATH: '/persons'
         21067 function calls (20695 primitive calls) in 0.027 seconds
```

**Comment by akira-dev** [comment]
New release is available on pypi with bug fix of this issue

**Comment by akira-dev** [comment]
Thank you very much for your contribution
