### ISSUE TITLE
api example SQLALCHEMY warning

### ISSUE THREAD

**Issue by OneVoltTen** [miLibris/flask-rest-jsonapi#37]
`FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '`
`app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False` resolved this warning.

**Comment by akira-dev** [comment]
Yes you are right. Thx. Fixed in 94e5a81a0e00030798624ef0aebfe9c9c2641f7f
