### ISSUE TITLE
Successful DELETE not returning propper response

### ISSUE THREAD

**Issue by renefs87** [miLibris/flask-rest-jsonapi#39]
Hi, I think that according to the jsonapi specification (http://jsonapi.org/format/#document-meta), DELETE should return a meta object, but this library is returning a string.
Incorrect:
```{
  "meta": {
    "Object successful deleted"
  },
  "jsonapi": {
    "version": "1.0"
  }
}
```
Correct:
```{
  "meta": {
    "result": "Object successful deleted"
  },
  "jsonapi": {
    "version": "1.0"
  }
}
```

I was having problems using this lib until I figured this out.
Cheers.

**Comment by akira-dev** [comment]
Fixed in 50b040bb2849a78fffbf0cf17e7c5e4db21cffac
