### ISSUE TITLE
Support for tornado?

### ISSUE THREAD

**Issue by stefanoborini** [miLibris/flask-rest-jsonapi#40]
Hello,

I need a library like flask-rest-jsonapi, but using tornado instead. In your opinion, how hard would it be for me to port it to tornado? From the code it seems relatively straightforward.
Alternatively, are you aware of any package providing a similar API and technical level, but for tornado?

Thanks

**Comment by akira-dev** [comment]
I'm not away of this kind of library and I know what is tornado but I never used it before. But Flask-REST-JSONAPI is very flexible so everything is possible.

**Comment by stefanoborini** [comment]
I am writing my own library, getting heavily inspired by your design. I checked if I could port it simply, but tornado supports async and it makes it a bit harder to integrate.
