### ISSUE TITLE
Question: Adding decororators to specific methods

### ISSUE THREAD

**Issue by krypttr** [miLibris/flask-rest-jsonapi#45]
Is it possible to add decorators to specific methods? For example I want to add a decorator for authorization on an endpoint's POST method. However I want GET method to be public.

**Comment by shubham-padia** [comment]
Yes, it is possible. Here is an example for the same where `is_admin` is a decorator.
```
post = is_admin(ResourceList.post.__func__)
```
If you've done this, do not mention is_admin in decorators = (is_admin, )

**Comment by krypttr** [comment]
Thank you this works but my specific problem is that I have two decorators. One jwt_required of flask-jwt-extended and another one roles_required(string role) for managing role based auth. roles_required decorator uses get_current_identity function which is provided by jwt_required decorator. So I used to something like this:
`@jwt_required
@roles_required("admin")
def POST(self):
etc`

How can I do this with flask-rest-jsonapi.

**Comment by shubham-padia** [comment]
I've not tried this, but this should work:
```python
post = jwt_required(ResourceList.post.__func__)
post = is_admin(ResourceList.post.__func__)
```
Keep in my mind the order of both.

Alternatively what we've done in our project is use second order decorators. So if jwt_required is needed each time roles_required is called, you can apply jwt_required decorator to roles_required itself.
The relevant code is at: https://github.com/fossasia/open-event-orga-server/blob/nextgen/app/api/helpers/permissions.py , please go through the SO link for more on second_order decorator.

Also I think you might have to have to modify your jwt_required function also for flask-rest-jsonapi, atleast we had to do it : 
```python
def jwt_required(fn, realm=None):
    """
    Modified from original jwt_required to comply with `flask-rest-jsonapi` decorator conventions
    View decorator that requires a valid JWT token to be present in the request
    :param realm: an optional realm
    """
    @wraps(fn)
    def decorator(*args, **kwargs):
        _jwt_required(realm or app.config['JWT_DEFAULT_REALM'])
        return fn(*args, **kwargs)
    return decorator
```

**Comment by krypttr** [comment]
It has been very helpful thank you very much!

**Comment by shubham-padia** [comment]
@krypttr Can you post the error please.

**Comment by krypttr** [comment]
```
Traceback (most recent call last):
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\WEB\Project1\flask\lib\site-packages\flask_rest_jsonapi\decorators.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "E:\WEB\Project1\flask\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\WEB\Project1\flask\lib\site-packages\flask_rest_jsonapi\resource.py", line 72, in dispatch_request
    raise e
BuildError: Could not build url for endpoint 'stuff_detail'. Did you forget to specify values ['user_id']?
```

**Comment by shubham-padia** [comment]
@krypttr As far as I can tell, that is an error with your endpoint, does the endpoint work without jwt_required, i.e without any authentication

**Comment by krypttr** [comment]
Yes it works for GET calls for example.

This doesn't work

`get= jwt_required(ResourceList.post.__func__)`

But this does

`decorators = (jwt_required,)`

**Comment by krypttr** [comment]
For ease of testing, I switched to GET method.

The following doesn't work

`get = jwt_required(ResourceList.get.__func__)`

But the following does

`decorators = (jwt_required,)`

**Comment by shubham-padia** [comment]
That's weird :/ . Cannot say for sure right now.

**Comment by krypttr** [comment]
For your information, I figured out that I can decorate the before_post method of the ResourceManager to only decorate the POST method. The following seems to work fine.

```python
@jwt_required
@roles_required("admin")
before_post(*args, **kwargs):
    pass
```

**Comment by shubham-padia** [comment]
Cool !! Thanks @krypttr :)
