### ISSUE TITLE
  AttributeError: 'SqlalchemyDataLayer' object has no attribute 'resource'

### ISSUE THREAD

**Issue by tzimme** [miLibris/flask-rest-jsonapi#46]
I'm trying to move from flask-restless to rest-jsonapi, but i'm getting an attributeerror as soon as i include a resource.

e.g. in my model i have a user-class:
```
class User(Base):
    uid = db.Column(db.String(100), unique = True)
    password = db.Column(PasswordType(schemes=app.config['PASSWORD_SCHEMES']), nullable=False)
    name = db.Column(db.String(100))
    email = db.Column(EmailType)
```

with this schema:
```
class UserSchema(Schema):
    class Meta:
        type_ = 'user'
        self_view = 'user_detail'
        self_view_kwargs = {'id':'<id>'}
        self_view_many = 'user_list'

    uid = fields.Str(dump_only=True)
    name = fields.Str(required=True,load_only=True)
    email = fields.Email(load_only=True)
    display_name = fields.Function(lambda obj: "{} <{}>".format(obj.name, obj.email))
    projects=Relationship(self_view='user_projects',
                          self_view_kwargs={'id':'<id>'},
                          related_view='project_list',
                          related_view_kwargs={'id':'<id>'},
                          many=True,
                          schema='ProjectSchema',
                          type_='project')
```

but including
```
class UserList(ResourceList):
    schema = UserSchema
    data_layer = {'session': db.session,
                  'model ': User}
```

causes:

>   File "/home/tzimme/.local/lib/python3.5/site-packages/project/rest.py", line 265, in <module>
>     class UserList(ResourceList):
>   File "/home/tzimme/.local/lib/python3.5/site-packages/flask_rest_jsonapi/resource.py", line 39, in __new__
>     rv._data_layer = data_layer_cls(data_layer_kwargs)
>   File "/home/tzimme/.local/lib/python3.5/site-packages/flask_rest_jsonapi/data_layers/alchemy.py", line 26, in __init__
>     .format(self.resource.__name__))
> AttributeError: 'SqlalchemyDataLayer' object has no attribute 'resource'

**Comment by Natureshadow** [comment]
I am pretty sure `'model '` is written without a space ☺.

**Comment by akira-dev** [comment]
You're right
