### ISSUE TITLE
Source tarball

### ISSUE THREAD

**Issue by Natureshadow** [miLibris/flask-rest-jsonapi#57]
In order to include Flask-REST-JSONAPI in the Debian distribution, please publish a source tarball on PyPI. Please make sure it contains the license, all documentation and tests and ideally sign it with a verifiable GPG key.

**Comment by rockstar** [comment]
Along with Debian, [wheels are still not supported by setuptools](https://packaging.python.org/discussions/pip-vs-easy-install/#pip-vs-easy-install), so anyone using this library as a dependency *can't* use `setup.py install` without some bootstrapping.

Please fix this soon. If you're already building wheels regularly, a release should be relatively easy to mirror for a source distribution as well.

**Comment by akira-dev** [comment]
Done
