### ISSUE TITLE
Default PAGE_SIZE not set in __init__

### ISSUE THREAD

**Issue by jcampbell** [miLibris/flask-rest-jsonapi#64]
The recent change to using a default PAGE_SIZE from app.config causes a KEY_ERROR if the PAGE_SIZE config option is not set, as it is not by default when initializing an API object from an existing Flask app (as is done in most of the documentation).

The simplest fix seems to be to ensure the default page size is set in __init__ in addition to init_app() of the Api class, although the tests and documentation seem split about the preferred way to construct the Api object.

**Comment by hellupline** [comment]
@akira-dev was this one closed on #74 ?

**Comment by jcampbell** [comment]
Yes, this should be closed.
