### ISSUE TITLE
Filter related objects after getting relationship

### ISSUE THREAD

**Issue by itsjef** [miLibris/flask-rest-jsonapi#66]
I am working on a problem that needs filtering out related objects that doesn't belong to the currently logged in user, which means I can't implement the query filter in my model or database.

Here, I intend to override `after_get_relationship` method and apply my filter there, but according to [how it's called in `get_relationship`](https://github.com/miLibris/flask-rest-jsonapi/blob/master/flask_rest_jsonapi/data_layers/alchemy.py#L255), the filter won't be applied thus doesn't affect the final result. I also tried iterating through the list of `related_objects` and call `del` on objects that needs to be filtered, but that didn't help.

My question is what should I do to achieve what I intended?

**Comment by akira-dev** [comment]
I think that the filtering system is now enough flexible and powerfull to fit your needs.
https://flask-rest-jsonapi.readthedocs.io/en/latest/filtering.html#sqlalchemy
