### ISSUE TITLE
Package crashes during the import.

### ISSUE THREAD

**Issue by rakenrol** [miLibris/flask-rest-jsonapi#8]
Package crashes during the import. MongoDataLayer is used here: https://github.com/miLibris/flask-rest-jsonapi/blob/master/flask_rest_jsonapi/__init__.py. One still needs to install pymongo to get the framework working.

Best Regards.

**Comment by akira-dev** [comment]
Thx for the issue. Fixed in https://github.com/miLibris/flask-rest-jsonapi/commit/b06754d6f70d5f82ab7dc74ac8fa7b7d691c5938

**Comment by rakenrol** [comment]
Thnx for fixing. BR.
