### ISSUE TITLE
it does not work for aliased column

### ISSUE THREAD

**Issue by ShigeruNakagaki** [miLibris/flask-rest-jsonapi#84]
If column of model uses alias like bellow, id matching does not work.
```
hoge_id = Column('id', Integer, primary_key=True)
```
line 72 of `data_layers/alchemy.py` should not be `getattr(self.model, id_field)`.

thanks

**Comment by hellupline** [comment]
why not use `id` as field name in the model?

**Comment by lepichon** [comment]
I think or has been fixed in https://github.com/miLibris/flask-rest-jsonapi/commit/83fd9948fe0732b6c9320538ea233b189507e918

**Comment by akira-dev** [comment]
Yes you're right @lepichon
