### ISSUE TITLE
Operator 'in' does not work with null value

### ISSUE THREAD

**Issue by AndreNalevaiko** [miLibris/flask-rest-jsonapi#90]
In version 0.12.5 was corrected the comparison between null value in the operator 'eq'. But in the operator 'in' the same thing is not working.

filter : `{"name":"category_id","op":"in","val":[1,null]}`

**Comment by akira-dev** [comment]
Have you tried to use or instead of in ?

**Comment by AndreNalevaiko** [comment]
> Have you tried to use or instead of in ?

With 'or' is working. But should not work with 'in'?

**Comment by akira-dev** [comment]
It is a sql behavior it is not related to this library
