### ISSUE TITLE
How to set a null value in patch?

### ISSUE THREAD

**Issue by AndreNalevaiko** [miLibris/flask-rest-jsonapi#91]
I am having trouble making the patch for null value.
Everything is nullable to field.

Error
`
{
    "errors": [
        {
            "detail": "Field may not be null.",
            "source": {
                "pointer": "/data/attributes/to_contact"
            },
            "status": "422",
            "title": "Validation error"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}
`

Schema
`class SentenceSchema(Schema):
    class Meta:
        type_ = 'sentence'
        self_view = 'api.sentence_detail'
        self_view_kwargs = {'id': '<id>'}
        self_view_many = 'api.sentence_list'

    id = fields.Integer(as_string=True)
    source = fields.String()
    from_contact = fields.String()
    to_contact = fields.String()
    contact_id = fields.Integer()
`

Model
ModelBase has key id

`class Sentence(ModelBase, db.Model):

    source = db.Column(db.Enum(*[e.value for e in Source]), nullable=True)
    from_contact = db.Column(db.String(128), nullable=True)
    to_contact = db.Column(db.String(128), nullable=True)
    contact_id = db.Column(db.Integer, nullable=True)
`

**Comment by AndreNalevaiko** [comment]
Sorry for the formatting, it was the best I could get through git

**Comment by akira-dev** [comment]
I think you have to specify the option allow_none=True in your schema fields

**Comment by AndreNalevaiko** [comment]
> I think you have to specify the option allow_none=True in your schema fields

that's rigtht. thanks!
